### ISSUE TITLE
Pick une langue maybe

### ISSUE THREAD

**Issue by DavidBruant** [daktary-team/file-moi-les-clefs#1]
Les messages de commits sont en anglais
Cards in the github projects are in French

ou au moins let's talk about it

**Comment by pointbar** [comment]
@DavidBruant - Ça ne me gênait pas, et là je suis plus très sûr.
Cool, d'échanger avec toi là-dessus.

**Comment by pointbar** [comment]
Il faut que je reprenne ce [commit](https://github.com/daktary-team/file-moi-les-clefs/commit/f6ffa5938c58efc640492f3b93ee4ab7eab2ad60) qui est presque en français pour le passer en anglais. Tu le penses aussi ?

**Comment by DavidBruant** [comment]
Le fait d'utiliser plusieurs langues m'embête surtout pour le futur
Les lecteurs du repo pourront survivre l'incohérence de langue du début, j'imagine

De la manière dont je vois les choses, si on utilise deux langues, j'ai l'impression qu'on exclut toutes les personnes qui ne lisent pas les deux langues couramment. Avec une langue, on n'exclut plus que les personnes qui ne parlent pas la seule langue choisie, (et on gagne potentiellement en facilité de traduction automatisée mais ce second point est très loin)
On en parle quand on se voit, aucune urgence de toute manière

**Comment by DavidBruant** [comment]
We have chosen English from now on
